http://localhost:3000/placares

###

http://localhost:3000/placares?usuario=Kyler


###

http://localhost:3000/placares/5


###

http://localhost:3000/placares?score_gte=5


###

http://localhost:3000/placares?score_gt=2